"""create learning_resources table

Revision ID: 9bd5ef6ad2a1
Revises: 8b7d8f0de9ae
Create Date: 2026-10-01 01:34:37.668834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd5ef6ad2a1'
down_revision: Union[str, None] = '8b7d8f0de9ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('THEORY_INTERVIEW', 'TECHNICAL_PRACTICAL', name='learning_mode'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'mode', 'url', name='uq_learning_resource')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_resources')
    # ### end Alembic commands ###
    # Autogenerate drops the table but not the enum type it created; drop it too so a
    # downgrade leaves no orphaned type behind (same as the evidence_type migration).
    sa.Enum(name='learning_mode').drop(op.get_bind(), checkfirst=True)
