"""create learning_progress table

Revision ID: e034a498adb5
Revises: 9bd5ef6ad2a1
Create Date: 2026-10-01 14:17:04.178411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e034a498adb5'
down_revision: Union[str, None] = '9bd5ef6ad2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STUDYING', 'FINISHED', name='learning_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_learning_progress')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_progress')
    # ### end Alembic commands ###
    # Autogenerate drops the table but not the enum type it created; drop it too
    # (same fix as the learning_mode and evidence_type migrations).
    sa.Enum(name='learning_status').drop(op.get_bind(), checkfirst=True)
